# Generated by Django 2.2.1 on 2019-05-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=120)),
                ('format', models.CharField(db_index=True, max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
