# Generated by Django 2.2.1 on 2019-05-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='format',
            field=models.CharField(choices=[('news', 'news'), ('faq', 'faq'), ('longread', 'longread')], db_index=True, max_length=10),
        ),
    ]
